
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import ClientProviders from "./components/clientProvider";
import RouteGuard from "./components/guard/routeGuard";
import useAutoLogout from "./components/timeout";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //  useAutoLogout();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProviders>
        <ToastContainer />
          <RouteGuard>{children}</RouteGuard>
        </ClientProviders>
      </body>
    </html>
  );
}
