


export const roleBasedRoutes = {
    Admin: ['/dashboard', '/view-resource','/view-resource/[id]/editResource', '/addResource','/view-resource/[id]/resourceDetails','/reports','/viewuser','/viewuser/[id]/edit','/addaviator','/verbalquiz','/verbalquiz/[id]/edit',
    '/userRender/view-resource',
    '/userRender/verbal',
    '/userRender/verbal/[id]/result',
    '/community/[id]/questiondetail',
    "/nonverbalquiz",
    '/addjet',
    '/addResorce',
    '/reports',
    '/notifications',
    '/results',
    '/suggestion',


    "/verbalquiz",
    '/userRender/verbal/[id]/attempt',
    '/competencyEvaluation/competency',
    '/userRender/addCommunityQuestion',
    '/userRender/viewCommunityQuestions',

      '/userRender/chat/[id]',
      '/certificate-page',
      '/certificate-page/[id]/editCertificate',
      '/certificate-page/[id]/certificateDetails',
      '/view-resource/[id]/resourceDetails',
      "/complaints/viewComplaints",
      "/notification/viewNotification",
      "/community",
      '/verbalquiz',
      '/nonverbalquiz',
      '/nonverbalquiz/[id]/edit',
      '/verbalquiz/[id]/edit',
      "/suggestion/viewsuggestion",
      'viewCommunityQuestions/[id]',
      '/userRender/verbal' ,
      '/forgetpassword',
      '/setpassword',
      '/userRender/nonverbal/[id]/result',
      '/userRender/nonverbal/[id]/attempt',
      '/userRender/nonverbal' ,
      '/userRender/viewCommunityQuestions/[id]/questionDetail',,
      '/quizPage',
      '/add-certificate',
      '/results/addResults',
      '/results/viewresults',
      '/results/viewresults[id]/detailResult',
      '/results/viewresults[id]/editResult',
      'reports',
      '/viewjets','/verbalquiz','/viewCommunityQuestions','/dashboard','/suggestion','results','/setpassword','results','quizPage','/notification','/nonverbalquiz','forgetpassword','complaints','community','CertificatesPage','/competency/form'],
    Aviator: ['/login','/signup','/userRender/addCommunityQuestion',
      '/userRender/chat/[id]',
      '/competencyEvaluation/competency',
      '/userRender/verbal/[id]/result',
      '/userRender/verbal/[id]/attempt',
      '/add-certificat',
      '/userRender/verbal' ,
      '/userRender/nonverbal/[id]/result',
      '/userRender/nonverbal/[id]/attempt',
      '/userRender/nonverbal' ,
      '/forgetpassword',
      '/setpassword',
      '/results/addResults',
      '/results/viewresults',
      '/results/viewresults[id]/detailResult',
      '/results/viewresults[id]/editResult',
      '/quizPage',
      '/community/[id]/questiondetail',
     ' /userRender/viewCommunityQuestions/[id]/questionDetail',
       '/userRender/viewCommunityQuestions','/userRender/viewCommunityQuestions/[id]/questionDetail','/forgetpassword','/setpassword','/chat','userRender/chat/[id]'
      ,'/userRender/view-resource' ],
  };
  
  export const publicRoutes = ['/login', '/signup','/']; 
  